version: '3'

services:
  mediawiki:
    image: mediawiki
    container_name: mediawiki
    restart: unless-stopped
    
    volumes:
      - images:/var/www/html/images
      #- data:/var/www/data
    
    ports:
      - 8481:80
    labels:
      - traefik.http.routers.ghost.rule=Host(`mediawiki.space.localhost`)
      - traefik.http.routers.ghost.service=mediawiki
      - traefik.http.services.ghost.loadbalancer.server.port=80
      - flame.type=app
      - flame.name=Mediawiki
      - flame.url=http://mediawiki.space.localhost
      - flame.icon=wikipedia

volumes:
  images: {}
  # data: {} # If you are using SQLite you can map this volume to "/var/www/data"
