version: '3'

services:
  adguard_exporter:
    image: ebrianne/adguard-exporter:latest
    container_name: adguard-exporter
    restart: unless-stopped
    
    env_file: docker-compose.env
    
    ports:
      - 9101:9617