# docker run -v `pwd`:/data -p 5000:5000 --rm -it sigoden/dufs /data -A

version: '3'

services:
  dufs:
    image: sigoden/dufs
    command: /data -A
    container_name: dufs
    restart: unless-stopped

    volumes:
      - ~/backup:/data
    
    ports:
      - 8487:5000
    labels:
      - traefik.http.routers.dufs.rule=Host(`dufs.space.localhost`)
      - traefik.http.routers.dufs.service=dufs
      - traefik.http.services.dufs.loadbalancer.server.port=5000
      - flame.type=app
      - flame.name=Dufs
      - flame.url=http://dufs.space.localhost
      - flame.icon=folder