version: '3'

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped

    volumes:
      - ~/backup/Media/Audiobooks:/audiobooks
      - ~/backup/Media/Podcasts:/podcasts
      - config:/config
      - metadata:/metadata
    
    env_file: docker-compose.env

    ports:
      - 8486:80
    labels:
      - traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.space.localhost`)
      - traefik.http.routers.audiobookshelf.service=audiobookshelf
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=80
      - flame.type=app
      - flame.name=audiobookshelf
      - flame.url=http://audiobookshelf.space.localhost
      - flame.icon=book-music

volumes:
  config: {}
  metadata: {}