version: '3'

services:
  komga:
    image: gotson/komga
    container_name: komga
    restart: unless-stopped
    
    volumes:
      - config:/config
      - data:/data
      - /etc/timezone:/etc/timezone:ro
    
    env_file: docker-compose.env

    ports:
      - 8482:8080
    labels:
      - traefik.http.routers.komga.rule=Host(`komga.space.localhost`)
      - traefik.http.routers.komga.service=komga
      - traefik.http.services.komga.loadbalancer.server.port=80
      - flame.type=app
      - flame.name=Komga
      - flame.url=http://komga.space.localhost
      - flame.icon=book-account

volumes:
  config: {}
  data: {s}