version: '3'

services:
  statping:
    image: statping/statping:dev
    container_name: statping
    restart: unless-stopped

    volumes:
      - app:/app
    
    env_file: docker-compose.env

    ports:
      - 8086:8080
    labels:
      - traefik.http.routers.statping.rule=Host(`statping.space.localhost`)
      - traefik.http.routers.statping.service=statping
      - traefik.http.services.statping.loadbalancer.server.port=8080
      - flame.type=app
      - flame.name=Statping
      - flame.url=http://statping.space.localhost
      - flame.icon=train-car-container

volumes:
  app: {}