version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    container_name: yourspotifyserver
    restart: unless-stopped
    
    links:
      - mongo
    depends_on:
      - mongo
    
    env_file: docker-compose.env

    ports:
      - 8288:8080
    labels:
      - traefik.http.routers.yourspotifyserver.rule=Host(`ys-api.space.localhost`)
      - traefik.http.routers.yourspotifyserver.service=yourspotifyserver
      - traefik.http.services.yourspotifyserver.loadbalancer.server.port=8080
  mongo:
    image: mongo:4.2.22
    container_name: yourspotifydb
    restart: unless-stopped
  web:
    image: yooooomi/your_spotify_client
    container_name: yourspotifyweb
    restart: unless-stopped

    env_file: docker-compose.env

    ports:
      - 8289:3000
    labels:
      - traefik.http.routers.yourspotify.rule=Host(`ys.space.localhost`)
      - traefik.http.routers.yourspotify.service=yourspotify
      - traefik.http.services.yourspotify.loadbalancer.server.port=3000
      - flame.type=app
      - flame.name=Your Spotify
      - flame.url=http://ys.space.localhost
      - flame.icon=music-box-multiple
