version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    restart: unless-stopped

    volumes:
      - vaultwarden:/data
      - vaultwardenSSL:/ssl
    
    env_file: docker-compose.env

    ports:
      - 8081:80  # Vault port
    labels:
      - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.space.localhost`)
      - traefik.http.routers.vaultwarden.service=vaultwarden
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
      - flame.type=app
      - flame.name=Vaultwarden
      - flame.url=http://vaultwarden.space.localhost
      - flame.icon=lock

volumes:
  vaultwarden: {}
  vaultwardenSSL: {}