version: '3'

services:
  guacamole:
    image: oznu/guacamole # Add :armhf for arm devices (ie. Raspberry Pi) 
    container_name: guacamole

    volumes:
      - ~/containers/guacamole/config:/config

    ports:
      - 8187:8080
    labels:
      - traefik.http.routers.guacamole.rule=Host(`guacamole.space.localhost`)
      - traefik.http.routers.guacamole.service=guacamole
      - traefik.http.services.guacamole.loadbalancer.server.port=8080
      - flame.type=app
      - flame.name=Guacamole
      - flame.url=http://localhost:8187
      - flame.icon=remote-desktop
