version: '3'

services:
  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped

    volumes:
      - data:/app/data
    
    ports:
      - 8389:80
    labels:
      - traefik.http.routers.gotify.rule=Host(`gotify.space.localhost`)
      - traefik.http.routers.gotify.service=gotify
      - traefik.http.services.gotify.loadbalancer.server.port=80
      - flame.type=app
      - flame.name=Gotify
      - flame.url=http://gotify.space.localhost
      - flame.icon=message-badge-outline

volumes:
  data: {}