version: '3'

services:
  emby:
    image: emby/embyserver
    container_name: emby
    restart: unless-stopped
    
    volumes:
      - emby:/config
      - embyCache:/cache
      #- ~/backup/Media:/media
    
    network_mode: host # Enable DLNA and Wake-on-Lan
    ports:
      - 8681:8096 # HTTP port
      - 8682:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
      - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    restart: unless-stopped

volumes:
  emby: {}
  embyCache: {}
