version: '3'

services:
  emby:
    image: emby/embyserver
    container_name: emby
    restart: unless-stopped
    
    volumes:
      - config:/config
      - cache:/cache
      #- ~/backup/Media:/media
    
    #network_mode: host # Enable DLNA and Wake-on-Lan
    ports:
      - 8681:8096 # HTTP port
      - 8682:8920 # HTTPS port
    labels:
      - traefik.http.routers.emby.rule=Host(`emby.space.localhost`)
      - traefik.http.routers.emby.service=emby
      - traefik.http.services.emby.loadbalancer.server.port=8096
      - flame.type=app
      - flame.name=Emby
      - flame.url=http://emby.space.localhost
      - flame.icon=multimedia

volumes:
  config: {}
  cache: {}
