version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped

    volumes:
      - ~/containers/pihole/pihole:/etc/pihole
      - ~/containers/pihole/dnsmasq.d:/etc/dnsmasq.d

    ports:
      - 53:53/tcp     #  DNS
      - 53:53/udp     # <-^
      - 9095:80/tcp   # webui
    labels:
      - traefik.http.routers.pihole.rule=Host(`pihole.space.localhost`)
      - traefik.http.routers.pihole.service=pihole
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - flame.type=app
      - flame.name=PiHole
      - flame.url=http://localhost:9095
      - flame.icon=dns