version: '3'

services:
  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    restart: unless-stopped

    volumes:
      - navidrome:/data
      - ~/backup/Media/Music:/music:ro
    
    env_file: docker-compose.env

    ports:
      - 4533:4533
    labels:
      - traefik.http.routers.navidrome.rule=Host(`navidrome.space.localhost`)
      - traefik.http.routers.navidrome.service=navidrome
      - traefik.http.services.navidrome.loadbalancer.server.port=4533
      - flame.type=app
      - flame.name=Navidrome
      - flame.url=http://navidrome.space.localhost
      - flame.icon=music

volumes:
  navidrome: {}