version: '3'

services:
  airsonic-advanced:
    image: lscr.io/linuxserver/airsonic-advanced
    container_name: airsonic-advanced
    restart: unless-stopped

    volumes:
      - airsonic-advanced:/config
      - ~/backup/Media/Music:/music
      - ~/backup/Media/Playlists:/playlists
      - ~/backup/Media/Podcasts:/podcasts

    env_file: docker-compose.env

    ports:
      - 8180:4040
    labels:
      - traefik.http.routers.airsonic.rule=Host(`airsonic.space.localhost`)
      - traefik.http.routers.airsonic.service=airsonic
      - traefik.http.services.airsonic.loadbalancer.server.port=4040
      - flame.type=app
      - flame.name=Airsonic
      - flame.url=http://airsonic.space.localhost
      - flame.icon=music-box-outline

volumes:
  airsonic-advanced: {}