version: '3'

services:
  traefik:
    image: traefik:v2.8
    command: --api.insecure=true --providers.docker
    container_name: traefik
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    ports:
      - 80:80      # HTTP port
      - 443:443    # HTTPS port
      - 9091:8080  # Web UI port
    labels:
      - traefik.http.routers.traefik.rule=Host(`traefik.space.localhost`)
      - traefik.http.routers.traefik.service=traefik
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - flame.type=app
      - flame.name=Traefik
      - flame.url=http://traefik.space.localhost
      - flame.icon=arrow-decision-outline