version: '3'

services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped

    volumes:
      - blocky:/app/config.yml

    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8285:4000/tcp
    labels:
      - traefik.http.routers.blocky.rule=Host(`blocky.space.localhost`)
      - traefik.http.routers.blocky.service=blocky
      - traefik.http.services.blocky.loadbalancer.server.port=4000
      - flame.type=app
      - flame.name=Blocky
      - flame.url=http://blocky.space.localhost
      - flame.icon=dns-outline

volumes:
  blocky: {}