version: "3"

services:
  moodle:
    image: moodlehq/moodleapp
    container_name: moodle
    restart: unless-stopped

    ports:
      - 8080:8080
    labels:
      - traefik.http.routers.moodle.rule=Host(`moodle.space.localhost`)
      - traefik.http.routers.moodle.service=moodle
      - traefik.http.services.moodle.loadbalancer.server.port=80
      - flame.type=app
      - flame.name=moodle
      - flame.url=http://moodle.space.localhost
      - flame.icon=school
