version: '3'

services:
  broker:
    image: docker.io/library/redis:6.0
    restart: unless-stopped

    volumes:
      - redis_data:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx
    container_name: Paperless-ngx
    restart: unless-stopped
    
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - export:/usr/src/paperless/export
      - consume:/usr/src/paperless/consume

    environment:
      PAPERLESS_REDIS: redis://broker:6379
    env_file: docker-compose.env    
    
    depends_on:
      - broker
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    
    ports:
      - 8188:8000
    labels:
      - traefik.http.routers.paperlessngx.rule=Host(`paperlessngx.space.localhost`)
      - traefik.http.routers.paperlessngx.service=paperlessngx
      - traefik.http.services.paperlessngx.loadbalancer.server.port=8000
      - flame.type=app
      - flame.name=Paperless-ngx
      - flame.url=http://paperlessngx.space.localhost
      - flame.icon=file

volumes:
  redis_data: {}
  data: {}
  media: {} 
  export: {}
  consume: {}