version: '3'

services:
  thelounge:
    image: thelounge/thelounge
    container_name: thelounge
    restart: unless-stopped

    volumes:
      - thelounge:/var/opt/thelounge

    ports:
      - 8185:9000
    labels:
      - traefik.http.routers.thelounge.rule=Host(`thelounge.space.localhost`)
      - traefik.http.routers.thelounge.service=thelounge
      - traefik.http.services.thelounge.loadbalancer.server.port=8080
      - flame.type=app
      - flame.name=The Lounge
      - flame.url=http://thelounge.space.localhost
      - flame.icon=alert-circle

volumes:
  thelounge: {}