version: '3'

services:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/containers/yacht/config:/config
    
    ports:
      - 9092:8000  # Web UI port
    labels:
      - traefik.http.routers.yacht.rule=Host(`yacht.space.localhost`)
      - traefik.http.routers.yacht.service=yacht
      - traefik.http.services.yacht.loadbalancer.server.port=80
      - flame.type=app
      - flame.name=Yacht
      - flame.url=http://localhost:9092
      - flame.icon=ferry