version: '3'

services:
  librespeed:
    image: adolfintel/speedtest
    container_name: librespeed
    restart: unless-stopped

    env_file: docker-compose.env

    ports:
      - 8090:80
    labels:
      - traefik.http.routers.librespeed.rule=Host(`librespeed.space.localhost`)
      - traefik.http.routers.librespeed.service=librespeed
      - traefik.http.services.librespeed.loadbalancer.server.port=80
      - flame.type=app
      - flame.name=LibreSpeed
      - flame.url=http://localhost:8090
      - flame.icon=speedometer