version: '3'

services:
  librespeed:
    image: linuxserver/librespeed
    container_name: librespeed
    restart: unless-stopped
    
    volumes:
      - config:/config
    
    ports:
      - 8090:80
    labels:
      - traefik.http.routers.librespeed.rule=Host(`librespeed.space.localhost`)
      - traefik.http.routers.librespeed.service=librespeed
      - traefik.http.services.librespeed.loadbalancer.server.port=80
      - flame.type=app
      - flame.name=LibreSpeed
      - flame.url=http://librespeed.space.localhost
      - flame.icon=speedometer

volumes:
  config: {}