version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    
    volumes:
      - config:/config
      - cache:/cache
      - ~/backup/Media:/media
    
    env_file: docker-compose.env

    #network_mode: "host"
    ports:
      - 8082:8096 # Jellyfin port
    labels:
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.space.localhost`)
      - traefik.http.routers.jellyfin.service=jellyfin
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - flame.type=app
      - flame.name=Jellyfin
      - flame.url=http://jellyfin.space.localhost
      - flame.icon=jellyfish-outline

volumes:
  config: {}
  cache: {}