version: '3'

services:
  web:
    image: ghcr.io/azuracast/azuracast
    container_name: azuracast
    restart: unless-stopped

    volumes:
      - azuracastUploads:/var/azuracast/uploads
      - azuracastStations:/var/azuracast/stations
      - azuracastBackup:/var/azuracast/backups
      - azuracastDB:/var/lib/mysql

    env_file: azuracast.env
    
    ports:
      - 8584:80
      - 8585:443
      - 4022:20221
    labels:
      - traefik.http.routers.azuracast.rule=Host(`azuracast.space.localhost`)
      - traefik.http.routers.azuracast.service=azuracast
      - traefik.http.services.azuracast.loadbalancer.server.port=80
      - flame.type=app
      - flame.name=AzuraCast
      - flame.url=http://azuracast.space.localhost
      - flame.icon=book-music

volumes:
  azuracastUploads: {}
  azuracastStations: {}
  azuracastBackup: {}
  azuracastDB: {}