version: '3'

services:
  subspace:
    image: subspacecloud/subspace
    container_name: subspace
    restart: unless-stopped

    cap_add:
      - NET_ADMIN

    volumes:
      - /usr/bin/wg:/usr/bin/wg
      - data:/data
    
    env_file: docker-compose.env

    network_mode: host

volumes:
  data: {}