version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    
    ports:
      - 8000:8000
      - 9092:9443
      # - 9000:9000
    labels:
      - traefik.http.routers.portainer.rule=Host(`portainer.space.localhost`)
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - flame.type=app
      - flame.name=Portainer
      - flame.url=http://portainer.space.localhost
      - flame.icon=train-car-container

volumes:
  data: {}