version: '3'

services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: unless-stopped

    cap_add:
      - SYS_PTRACE

    volumes:
      - ~/containers/netdata/config:/etc/netdata
      - ~/containers/netdata/lib:/var/lib/netdata
      - ~/containers/netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    
    ports:
      - 8489:19999
    labels:
      - traefik.http.routers.netdata.rule=Host(`netdata.space.localhost`)
      - traefik.http.routers.netdata.service=netdata
      - traefik.http.services.netdata.loadbalancer.server.port=8080
      - flame.type=app
      - flame.name=Netdata
      - flame.url=http://netdata.space.localhost
      - flame.icon=chart-donut