version: '3'

services:
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    restart: unless-stopped
    
    volumes:
      - data:/var/www/FreshRSS/data

    env_file: docker-compose.env

    ports:
      - 8485:80
    labels:
      - traefik.http.routers.freshrss.rule=Host(`freshrss.space.localhost`)
      - traefik.http.routers.freshrss.service=freshrss
      - traefik.http.services.freshrss.loadbalancer.server.port=80
      - flame.type=app
      - flame.name=FreshRSS
      - flame.url=http://freshrss.space.localhost
      - flame.icon=rss

volumes:
  data: {}