version: '3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:base-alpine
    container_name: uptime-kuma
    restart: unless-stopped
    
    ports:
      - 6082:8080
    labels:
      - traefik.http.routers.uptimekuma.rule=Host(`uptimekuma.space.localhost`)
      - traefik.http.routers.uptimekuma.service=uptimekuma
      - traefik.http.services.uptimekuma.loadbalancer.server.port=8080
      - flame.type=app
      - flame.name=Uptime Kuma
      - flame.url=http://uptimekuma.space.localhost
      - flame.icon=list-status