version: '3.5'

services:
  photoprism:
    container_name: photoprism
    image: photoprism/photoprism:arm64
    restart: unless-stopped
    working_dir: "/photoprism"

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    volumes:
      - "/media/beta/Backup/Pictures:/photoprism/originals"
      # - "~/Import:/photoprism/import"
      - "./storage:/photoprism/storage"

    env_file: docker-compose.env
    
    depends_on:
      - mariadb
    ports:
      - 8900:2342
    

  mariadb:
    container_name: photoprism_db
    image: mariadb:10.10
    restart: unless-stopped
    command: mysqld --innodb-buffer-pool-size=256M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    
    volumes:
      - "db:/var/lib/mysql"

volumes:
  db: {}