version: '3'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    container_name: nginx-proxy-manager
    restart: unless-stopped
    
    volumes:
      - data:/data
      - ssl:/etc/letsencrypt

    #network_mode: host
    ports:
      - 80:80    # HTTP port
      - 443:443  # HTTPS port
      - 9091:81  # Web UI port
    labels:
      - traefik.http.routers.lldap.rule=Host(`npm.space.localhost`)
      - traefik.http.routers.lldap.service=lldap
      - traefik.http.services.lldap.loadbalancer.server.port=17170
      - flame.type=app
      - flame.name="Nginx Proxy Manager"
      - flame.url=http://npm.space.localhost
      - flame.icon=arrow-decision-outline

volumes:
  data: {}
  ssl: {}