version: '3'

services:
  lidarr:
    image: youegraillot/lidarr-on-steroids
    container_name: lidarr-os
    restart: unless-stopped

    volumes:
      - config:/config
      - deemix_config:/config_deemix
      - downloads:/downloads
      - ~/backup/Music:/music
    
    ports:
      - "8380:8686" # Lidarr web UI
      - "8381:6595" # Deemix web UI
    labels:
      - traefik.http.routers.lidarr.rule=Host(`lidarr.space.localhost`)
      - traefik.http.routers.lidarr.service=lidarr
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - flame.type=app
      - flame.name=Lidarr
      - flame.url=http://lidarr.space.localhost
      - flame.icon=file-music

volumes:
  config: {}
  deemix_config: {}
  downloads: {}