version: '3'

services:
  deemix:
    image: registry.gitlab.com/bockiii/deemix-docker
    container_name: Deemix
    restart: unless-stopped

    volumes:
     - ~/backup/Media/Music:/downloads
     - config:/config

    env_file: docker-compose.env

    ports:
     - 6581:6595
    labels:
      - traefik.http.routers.deemix.rule=Host(`deemix.space.localhost`)
      - traefik.http.routers.deemix.service=deemix
      - traefik.http.services.deemix.loadbalancer.server.port=6595
      - flame.type=app
      - flame.name=Deemix
      - flame.url=http://deemix.space.localhost
      - flame.icon=file-music

volumes:
  config: {}