name: Update template

on:
  push:
    branches: [dev]
    paths:
      - "**.yml"
      - ".makeTemplate.py"

jobs:
  update:
    name: Update templates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          cache: pip
  #       cache-dependency-path: .requirements.txt
  
      - name: Update templates
        run: python3 .makeTemplate.py
  
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'templates.json'
          default_author: github_actions

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: ':sparkles: Updated template file!'
