version: '3'
services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    restart: unless-stopped

    volumes:
      - config:/config
      - data:/assets
    
    env_file: docker-compose.env

    ports:
      - 8084:8080
    labels:
      - traefik.http.routers.podgrab.rule=Host(`podgrab.space.localhost`)
      - traefik.http.routers.podgrab.service=podgrab
      - traefik.http.services.podgrab.loadbalancer.server.port=8080
      - flame.type=app
      - flame.name=Podgrab
      - flame.url=http://podgrab.space.localhost
      - flame.icon=folder

volumes:
  config: {}
  data: {}